# Generated by Django 3.0.7 on 2020-06-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('18-', 'Below 18 years'), ('18-30', '18-30 years'), ('30+', 'Above 30 years')], default=(('18-', 'Below 18 years'), ('18-30', '18-30 years'), ('30+', 'Above 30 years')), max_length=30, verbose_name='Under which age-group do you fall in?')),
            ],
        ),
    ]
