# Generated by Django 3.0.7 on 2020-06-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200615_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='age',
            field=models.CharField(choices=[('18-', 'Below 18 years'), ('18-30', '18-30 years'), ('30+', 'Above 30 years')], max_length=30),
        ),
    ]
