# Generated by Django 3.0.7 on 2020-06-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200615_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='currently_experiencing_symptoms',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], default=(('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')), max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='feelings_due_to_lockdown',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=(('yes', 'Yes'), ('no', 'No')), max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=(('male', 'Male'), ('female', 'Female'), ('other', 'Other')), max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='negative_effect',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], default=(('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')), max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='previously_suffered',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], default=(('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')), max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='therapist',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=(('yes', 'Yes'), ('no', 'No')), max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='age',
            field=models.CharField(choices=[('18-', 'Below 18 years'), ('18-30', '18-30 years'), ('30+', 'Above 30 years')], default=(('18-', 'Below 18 years'), ('18-30', '18-30 years'), ('30+', 'Above 30 years')), max_length=30),
        ),
    ]
