# Generated by Django 3.0.7 on 2020-06-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200615_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='feelings_due_to_lockdown',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Null', max_length=10),
        ),
    ]
