# Generated by Django 3.0.7 on 2020-06-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200621_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='therapist',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=10),
        ),
    ]
